# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    api.response_factory:
        class: AppBundle\Api\ResponseFactory

    api_exception_subscriber:
            class: AppBundle\EventListener\ApiExceptionSubscriber
            arguments: ['%kernel.debug%', '@api.response_factory']
            tags:
                - { name: kernel.event_subscriber }
